hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - pipeline=pipeline_all,pipeline_big,pipeline_small
  job:
    name: main
    chdir: null
    override_dirname: pipeline=pipeline_all,pipeline_big,pipeline_small
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.2'
    cwd: /Users/aaroncolombo/Documents/GitHub/MIALab/bin
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/aaroncolombo/Documents/GitHub/MIALab/bin/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      pipeline: pipeline_all
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
paths:
  data_atlas_dir: ${hydra:runtime.cwd}/../data/atlas
  data_train_dir_orig: ${hydra:runtime.cwd}/../data/train/
  data_test_dir_orig: ${hydra:runtime.cwd}/../data/test/
  gen_result_dir: ./multirun/
params:
  loading_keys_pipeline:
  - T1w
  - T2w
  - GroundTruth
  - BrainMask
  - RegistrationTransform
pipeline:
  name: pipeline_all
  paths:
    result_dir: ./multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/mia-result_all
    data_train_dir: ${hydra:runtime.cwd}/../data/train/
    data_test_dir: ${hydra:runtime.cwd}/../data/test/
  params:
    n_estimators: 10
    max_depth: 10
    pre_process_params:
      training: true
      skullstrip_pre: true
      normalization_pre: true
      registration_pre: true
      coordinates_feature: true
      intensity_feature: true
      gradient_intensity_feature: true
    labels:
      1: WhiteMatter
      2: GreyMatter
      3: Hippocampus
      4: Amygdala
      5: Thalamus
